function renderCompare(){
  const grid=$('#compareGrid');if(!grid)return;grid.innerHTML='';if(filter!=='saved')return;const b=current(),a=(b.items||[]).filter(x=>(b.saved||[]).includes(x.id));
  if(!a.length){grid.innerHTML='<div class="compare-empty">Save a few finds first, then compare them here.</div>';return}
  a.forEach(x=>{const c=document.createElement('article');c.className='compare-card';const img=x.image?`<img src="${escapeHTML(x.image)}" alt="" referrerpolicy="no-referrer" onerror="this.remove()">`:'Visual unavailable';const reviews=x.reviews||x.rating||'—';c.innerHTML=`<div class="compare-img">${img}</div><div class="compare-body"><div class="compare-src">${escapeHTML(x.source||'Inspo')}</div><div class="compare-title">${escapeHTML(x.title||'Untitled find')}</div>${compareRow('Price',x.price)}${compareRow('Size',x.size)}${compareRow('Reviews',reviews)}${compareRow('Condition',x.condition)}${x.url?`<a class="compare-open" href="${escapeHTML(x.url)}" target="_blank" rel="noopener">Open source</a>`:''}</div>`;grid.appendChild(c)})
}
function compareRow(label,value){return `<div class="compare-row"><span>${label}</span><b>${escapeHTML(value||'—')}</b></div>`}
function parseDetails(text=''){const s=String(text).replace(/\s+/g,' ').trim(),out={};let m=s.match(/\$\s?\d+(?:[.,]\d{2})?/);if(m)out.price=m[0].replace(/\s+/g,'');m=s.match(/(?:size|sized)\s*[:\-]?\s*(XXS|XS|S|M|L|XL|XXL|XXXL|\d{1,2}(?:\s*[-–]\s*\d{1,2})?)/i);if(m)out.size=m[1].toUpperCase();m=s.match(/([0-5](?:\.\d)?)\s*(?:out of 5|stars?|★)/i);const r=s.match(/([\d,]+)\s*(?:ratings?|reviews?)/i);if(m||r)out.reviews=[m?m[1]+' ★':'',r?r[1]+' reviews':''].filter(Boolean).join(' · ');m=s.match(/\b(new with tags|new without tags|very good|good|satisfactory|used|new)\b/i);if(m)out.condition=m[1].replace(/\b\w/g,c=>c.toUpperCase());return out}
async function enrichItem(x,force=false){if(!x?.url)return false;if(!force&&x.detailsChecked&&x.image&&x.price&&x.size)return false;try{const d=await preview(x.url);let changed=false;if(d.image&&(!x.image||force)){x.image=d.image;changed=true}if(d.title&&(!x.title||/^(Amazon|Vinted|Inspo) (outfit option|find)$/i.test(x.title))){x.title=d.title;changed=true}if(d.source){const s=sourceName(x.url,d.source);if(s&&s!==x.source){x.source=s;changed=true}}const det=parseDetails([d.title,d.description].filter(Boolean).join(' '));for(const k of ['price','size','reviews','condition'])if(det[k]&&(!x[k]||force)){x[k]=det[k];changed=true}x.detailsChecked=Date.now();return changed}catch{x.detailsChecked=Date.now();return false}}
async function refreshSavedDetails(){const b=current();if(!b)return;const a=(b.items||[]).filter(x=>(b.saved||[]).includes(x.id));if(!a.length){toast('Save a few finds first');return}$('#refreshDetails').disabled=true;$('#refreshDetails').textContent='Refreshing…';let changed=false;for(const x of a)changed=(await enrichItem(x,true))||changed;if(changed){b.updated=now();persist()}$('#refreshDetails').disabled=false;$('#refreshDetails').textContent='↻ Refresh details';renderBoard();toast(changed?'Details refreshed':'No new details found')}
async function hydrateMissing(){let changed=false;for(const b of projects){for(const x of (b.items||[])){if(x.url&&(!x.image||!x.detailsChecked))changed=(await enrichItem(x,false))||changed}}if(changed)persist();if(currentId)renderBoard();else renderHome()}
$('#savedBrowseBtn').onclick=()=>{savedMode='browse';renderBoard()};$('#savedCompareBtn').onclick=()=>{savedMode='compare';renderBoard();setTimeout(()=>refreshSavedDetails(),80)};$('#refreshDetails').onclick=refreshSavedDetails;
