function bytesToB64url(bytes){let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64urlToBytes(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const raw=atob(s);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
async function pack(obj){const data=new TextEncoder().encode(JSON.stringify(obj));if('CompressionStream'in window){const stream=new Blob([data]).stream().pipeThrough(new CompressionStream('gzip'));const buf=new Uint8Array(await new Response(stream).arrayBuffer());return'z'+bytesToB64url(buf)}return'b'+bytesToB64url(data)}
async function unpack(s){const mode=s[0],bytes=b64urlToBytes(s.slice(1));let out=bytes;if(mode==='z'&&'DecompressionStream'in window){const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));out=new Uint8Array(await new Response(stream).arrayBuffer())}return JSON.parse(new TextDecoder().decode(out))}
$('#shareBoard').onclick=async()=>{
  const b=current();if(!b)return;toast('Making share link…');try{const copy=clone(b);copy.id='shared-'+b.id;const code=await pack({v:1,board:copy});const url=location.origin+location.pathname+'#share='+code;const data={title:b.title,text:'I made an inspo board for you ✦',url};if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(url);toast('Share link copied')}}catch(e){if(e?.name!=='AbortError')toast('Could not make the share link')}
};
async function importShared(){
  if(!location.hash.startsWith('#share='))return false;try{const data=await unpack(location.hash.slice(7)),incoming=data?.board;if(!incoming?.title||!Array.isArray(incoming.items))throw 0;let existing=projects.find(p=>p.id===incoming.id);if(existing){currentId=existing.id}else{incoming.id=incoming.id||'shared-'+now();incoming.created=now();incoming.updated=now();incoming.saved=incoming.saved||[];projects.push(incoming);persist();currentId=incoming.id}history.replaceState(null,'',location.pathname+location.search);openBoard(currentId);toast('Shared board added to your projects');return true}catch{history.replaceState(null,'',location.pathname+location.search);toast('That shared board link could not be opened');return false}}
let touchX=0;$('#card').addEventListener('touchstart',e=>touchX=e.changedTouches[0].screenX,{passive:true});$('#card').addEventListener('touchend',e=>{const d=e.changedTouches[0].screenX-touchX;if(Math.abs(d)>55)move(d<0?1:-1)},{passive:true});
let toastTimer;function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),1400)}
(async()=>{if(!(await importShared()))renderHome();setTimeout(()=>hydrateMissing(),250)})();
